version: 0.0
os: windows
files:
  - source: /
    destination: C:\Users\Administrator\Desktop\httpd-2.4.29-win64-VC11\Apache24\htdocs
hooks:
  BeforeInstall:
    - location: scripts/server_startup.bat
      timeout: 900
  
     

